spring:
  config:
    # Java properties 형식의 필수 .env.local 구성
    import: "file:./.env.local[.properties]"

eureka:
  client:
    # Discovery 동시 실행 시 .env.local의 명시적 활성화
    enabled: ${EUREKA_ENABLED:false}
