CREATE TABLE identity_service.refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id UUID NOT NULL,
    family_id UUID NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revocation_reason VARCHAR(40),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_refresh_tokens_account
        FOREIGN KEY (account_id)
            REFERENCES identity_service.accounts (id),
    CONSTRAINT uq_refresh_tokens_hash
        UNIQUE (token_hash),
    CONSTRAINT ck_refresh_tokens_expiration
        CHECK (expires_at > created_at),
    CONSTRAINT ck_refresh_tokens_used_at
        CHECK (used_at IS NULL OR used_at >= created_at),
    CONSTRAINT ck_refresh_tokens_revoked_at
        CHECK (revoked_at IS NULL OR revoked_at >= created_at),
    CONSTRAINT ck_refresh_tokens_revocation
        CHECK (
            (revoked_at IS NULL AND revocation_reason IS NULL)
            OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)
        )
);

CREATE INDEX idx_refresh_tokens_account
    ON identity_service.refresh_tokens (account_id);

CREATE INDEX idx_refresh_tokens_family
    ON identity_service.refresh_tokens (family_id);
