-- 계정 상태 변경 감사와 마지막 SYSTEM_ADMIN 보호 기반
CREATE TABLE identity_service.account_status_change_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id UUID NOT NULL,
    target_user_id UUID NOT NULL,
    action VARCHAR(40) NOT NULL,
    before_status VARCHAR(20) NOT NULL,
    after_status VARCHAR(20) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    -- 향후 Request ID 연계를 위한 null 허용 예약 컬럼
    request_id VARCHAR(32),

    CONSTRAINT fk_account_status_change_audits_actor
        FOREIGN KEY (actor_user_id)
            REFERENCES identity_service.accounts (id),
    CONSTRAINT fk_account_status_change_audits_target
        FOREIGN KEY (target_user_id)
            REFERENCES identity_service.accounts (id),
    CONSTRAINT ck_account_status_change_audits_action
        CHECK (action IN (
            'ACCOUNT_DISABLED',
            'ACCOUNT_UNLOCKED',
            'ACCOUNT_REACTIVATED'
        )),
    CONSTRAINT ck_account_status_change_audits_before_status
        CHECK (before_status IN ('ACTIVE', 'LOCKED', 'DISABLED', 'WITHDRAWN')),
    CONSTRAINT ck_account_status_change_audits_after_status
        CHECK (after_status IN ('ACTIVE', 'LOCKED', 'DISABLED', 'WITHDRAWN')),
    CONSTRAINT ck_account_status_change_audits_reason
        CHECK (
            reason = BTRIM(reason)
            AND CHAR_LENGTH(reason) BETWEEN 1 AND 500
        ),
    CONSTRAINT ck_account_status_change_audits_transition
        CHECK (
            (
                action = 'ACCOUNT_DISABLED'
                AND before_status IN ('ACTIVE', 'LOCKED')
                AND after_status = 'DISABLED'
            )
            OR (
                action = 'ACCOUNT_UNLOCKED'
                AND before_status = 'LOCKED'
                AND after_status = 'ACTIVE'
            )
            OR (
                action = 'ACCOUNT_REACTIVATED'
                AND before_status = 'DISABLED'
                AND after_status = 'ACTIVE'
            )
        )
);

-- 마지막 관리자 확인 쿼리를 위한 부분 인덱스
CREATE INDEX idx_accounts_usable_system_admin
    ON identity_service.accounts (id)
    WHERE global_role = 'SYSTEM_ADMIN'
      AND status IN ('ACTIVE', 'LOCKED');

-- 관리자 감소 요청 직렬화를 위한 단일 보호 행
CREATE TABLE identity_service.system_administrator_guards (
    id SMALLINT PRIMARY KEY,

    CONSTRAINT ck_system_administrator_guards_singleton
        CHECK (id = 1)
);

INSERT INTO identity_service.system_administrator_guards (id)
VALUES (1);
