-- 전역 역할 변경 감사
--
-- V3의 account_status_change_audits 와 컬럼·제약 관례를 맞춘다.
-- 상태 변경과 역할 변경은 전이 규칙이 겹치지 않아 한 테이블에 담으면 CHECK 가
-- 서로를 무력화한다. 그래서 테이블을 나누고, 통합 조회가 필요하면 뷰로 합친다.
CREATE TABLE identity_service.account_role_change_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id UUID NOT NULL,
    target_user_id UUID NOT NULL,
    action VARCHAR(40) NOT NULL,
    before_role VARCHAR(20) NOT NULL,
    after_role VARCHAR(20) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    -- 향후 Request ID 연계를 위한 null 허용 예약 컬럼
    request_id VARCHAR(32),

    CONSTRAINT fk_account_role_change_audits_actor
        FOREIGN KEY (actor_user_id)
            REFERENCES identity_service.accounts (id),
    CONSTRAINT fk_account_role_change_audits_target
        FOREIGN KEY (target_user_id)
            REFERENCES identity_service.accounts (id),
    CONSTRAINT ck_account_role_change_audits_action
        CHECK (action IN (
            'ROLE_GRANTED',
            'ROLE_REVOKED'
        )),
    CONSTRAINT ck_account_role_change_audits_before_role
        CHECK (before_role IN ('USER', 'SYSTEM_ADMIN')),
    CONSTRAINT ck_account_role_change_audits_after_role
        CHECK (after_role IN ('USER', 'SYSTEM_ADMIN')),
    CONSTRAINT ck_account_role_change_audits_reason
        CHECK (
            reason = BTRIM(reason)
            AND CHAR_LENGTH(reason) BETWEEN 1 AND 500
        ),
    -- action 과 실제 전이가 어긋난 기록을 DB에서 막는다
    CONSTRAINT ck_account_role_change_audits_transition
        CHECK (
            (
                action = 'ROLE_GRANTED'
                AND before_role = 'USER'
                AND after_role = 'SYSTEM_ADMIN'
            )
            OR (
                action = 'ROLE_REVOKED'
                AND before_role = 'SYSTEM_ADMIN'
                AND after_role = 'USER'
            )
        )
);

-- "이 사용자의 권한이 언제 누구에 의해 바뀌었나"가 가장 잦은 조회다
CREATE INDEX idx_account_role_change_audits_target
    ON identity_service.account_role_change_audits (target_user_id, occurred_at DESC);
